FROM node:18 as development

WORKDIR /usr/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate

# Make startup script executable
RUN chmod +x startup.sh

EXPOSE 10000

CMD ["./startup.sh"]