services:
  # Backend API Service
  - type: web
    name: vial-query-backend
    env: docker
    dockerfilePath: ./Dockerfile.local
    plan: free
    buildCommand: npm install && npx prisma generate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vial-postgres
          property: connectionString
      - key: PORT
        value: 10000
    healthCheckPath: /health

databases:
  # PostgreSQL Database
  - name: vial-postgres
    databaseName: vial
    user: vial
    plan: free
    region: oregon 